".NET update":
 - any: [ 'src/global.json' ]
"C#":
 - any: [ './**/*.cs', './**/*.csproj' ]
"C# Project":
 - any: [ './**/*.csproj' ]
"C# Solution":
 - any: [ './**/*.sln', './**/*.slnx' ]
"Change Log":
 - any: [ 'CHANGELOG.md' ]
"Config Change":
 - any: [ 'src/**/*.json', '!src/global.json' ]
"credfeto-aur-mirror-config":
 - any: [ 'src/$Credfeto.Aur.Mirror.Config/**/*' ]
"credfeto-aur-mirror-git":
 - any: [ 'src/$Credfeto.Aur.Mirror.Git/**/*' ]
"credfeto-aur-mirror-git-interfaces":
 - any: [ 'src/$Credfeto.Aur.Mirror.Git.Interfaces/**/*' ]
"credfeto-aur-mirror-git-tests":
 - any: [ 'src/$Credfeto.Aur.Mirror.Git.Tests/**/*' ]
"credfeto-aur-mirror-interfaces":
 - any: [ 'src/$Credfeto.Aur.Mirror.Interfaces/**/*' ]
"credfeto-aur-mirror-models":
 - any: [ 'src/$Credfeto.Aur.Mirror.Models/**/*' ]
"credfeto-aur-mirror-rpc":
 - any: [ 'src/$Credfeto.Aur.Mirror.Rpc/**/*' ]
"credfeto-aur-mirror-rpc-interfaces":
 - any: [ 'src/$Credfeto.Aur.Mirror.Rpc.Interfaces/**/*' ]
"credfeto-aur-mirror-rpc-tests":
 - any: [ 'src/$Credfeto.Aur.Mirror.Rpc.Tests/**/*' ]
"credfeto-aur-mirror-server":
 - any: [ 'src/$Credfeto.Aur.Mirror.Server/**/*' ]
"github-actions":
 - any: [ '.github/workflows/*.yml' ]
"Markdown":
 - any: [ './**/*.md' ]
"Migration Script":
 - any: [ 'tools/MigrationScripts/**/*' ]
"Powershell":
 - any: [ './**/*.ps1', './**/*.psm1' ]
"Read Me":
 - any: [ 'README.md' ]
"Setup":
 - any: [ 'SETUP.md' ]
"Solidity":
 - any: [ './**/*.sol' ]
"SQL":
 - any: [ './**/*.sql', 'db/**/*' ]
"Static Code Analysis Rules":
 - any: [ 'src/CodeAnalysis.ruleset' ]
"Unit Tests":
 - any: [ 'src/*.Tests.*/**/*', 'src/*.Tests.Integration.*/**/*', 'src/*.Tests.Integration/**/*', 'src/*.Tests/**/*' ]
